start /b sqlcmd /E /S. /dCredit /i"Scenario J - Repro Traffic - A.sql"
start /b sqlcmd /E /S. /dCredit /i"Scenario J - Repro Traffic - B.sql"
start /b sqlcmd /E /S. /dCredit /i"Scenario J - Repro Traffic - C.sql"
start /b sqlcmd /E /S. /dCredit /i"Scenario J - Repro Traffic - A.sql"
start /b sqlcmd /E /S. /dCredit /i"Scenario J - Repro Traffic - B.sql"
start /b sqlcmd /E /S. /dCredit /i"Scenario J - Repro Traffic - C.sql"
start /b sqlcmd /E /S. /dCredit /i"Scenario J - Repro Traffic - A.sql"
start /b sqlcmd /E /S. /dCredit /i"Scenario J - Repro Traffic - B.sql"
start /b sqlcmd /E /S. /dCredit /i"Scenario J - Repro Traffic - C.sql"
start /b sqlcmd /E /S. /dCredit /i"Scenario J - Repro Traffic - A.sql"
start /b sqlcmd /E /S. /dCredit /i"Scenario J - Repro Traffic - B.sql"
start /b sqlcmd /E /S. /dCredit /i"Scenario J - Repro Traffic - C.sql"
start /b sqlcmd /E /S. /dCredit /i"Scenario J - Repro Traffic - A.sql"
start /b sqlcmd /E /S. /dCredit /i"Scenario J - Repro Traffic - B.sql"
start /b sqlcmd /E /S. /dCredit /i"Scenario J - Repro Traffic - C.sql"
start /b sqlcmd /E /S. /dCredit /i"Scenario J - Repro Traffic - A.sql"
start /b sqlcmd /E /S. /dCredit /i"Scenario J - Repro Traffic - B.sql"
start /b sqlcmd /E /S. /dCredit /i"Scenario J - Repro Traffic - C.sql"
start /b sqlcmd /E /S. /dCredit /i"Scenario J - Repro Traffic - A.sql"
start /b sqlcmd /E /S. /dCredit /i"Scenario J - Repro Traffic - B.sql"
start /b sqlcmd /E /S. /dCredit /i"Scenario J - Repro Traffic - C.sql"
start /b sqlcmd /E /S. /dCredit /i"Scenario J - Repro Traffic - A.sql"
start /b sqlcmd /E /S. /dCredit /i"Scenario J - Repro Traffic - B.sql"
start /b sqlcmd /E /S. /dCredit /i"Scenario J - Repro Traffic - C.sql"


