start sqlcmd -S(local)\SQL2014 -dSalesDB -iLoopingSalesFaster.sql
start sqlcmd -S(local)\SQL2014 -dSalesDB -iLoopingSalesFaster.sql
start sqlcmd -S(local)\SQL2014 -dSalesDB -iLoopingSalesFaster.sql
start sqlcmd -S(local)\SQL2014 -dSalesDB -iLoopingSalesFaster.sql
start sqlcmd -S(local)\SQL2014 -dSalesDB -iLoopingSalesFaster.sql
start sqlcmd -S(local)\SQL2014 -dSalesDB -iLoopingSalesFaster.sql
start sqlcmd -S(local)\SQL2014 -dSalesDB -iLoopingSalesFaster.sql
start sqlcmd -S(local)\SQL2014 -dSalesDB -iLoopingSalesFaster.sql
start sqlcmd -S(local)\SQL2014 -dSalesDB -iLoopingSalesFaster.sql
start sqlcmd -S(local)\SQL2014 -dSalesDB -iLoopingSalesFaster.sql
start sqlcmd -S(local)\SQL2014 -dSalesDB -iLoopingSalesFaster.sql
start sqlcmd -S(local)\SQL2014 -dSalesDB -iLoopingSalesFaster.sql
start sqlcmd -S(local)\SQL2014 -dSalesDB -iLoopingSalesFaster.sql
start sqlcmd -S(local)\SQL2014 -dSalesDB -iLoopingSalesFaster.sql
start sqlcmd -S(local)\SQL2014 -dSalesDB -iLoopingSalesFaster.sql
start sqlcmd -S(local)\SQL2014 -dSalesDB -iLoopingSalesFaster.sql
start sqlcmd -S(local)\SQL2014 -dSalesDB -iLoopingSalesFaster.sql
start sqlcmd -S(local)\SQL2014 -dSalesDB -iLoopingSalesFaster.sql
start sqlcmd -S(local)\SQL2014 -dSalesDB -iLoopingSalesFaster.sql
start sqlcmd -S(local)\SQL2014 -dSalesDB -iLoopingSalesFaster.sql
