start sqlcmd -S(local)\SQL2012Dev01 -dSalesDB -iLoopingCustomers.sql
start sqlcmd -S(local)\SQL2012Dev01 -dSalesDB -iLoopingCustomers.sql
start sqlcmd -S(local)\SQL2012Dev01 -dSalesDB -iLoopingCustomers.sql
start sqlcmd -S(local)\SQL2012Dev01 -dSalesDB -iLoopingCustomers.sql
start sqlcmd -S(local)\SQL2012Dev01 -dSalesDB -iLoopingCustomers.sql
start sqlcmd -S(local)\SQL2012Dev01 -dSalesDB -iLoopingCustomers.sql
start sqlcmd -S(local)\SQL2012Dev01 -dSalesDB -iLoopingCustomers.sql
start sqlcmd -S(local)\SQL2012Dev01 -dSalesDB -iLoopingCustomers.sql
start sqlcmd -S(local)\SQL2012Dev01 -dSalesDB -iLoopingCustomers.sql
start sqlcmd -S(local)\SQL2012Dev01 -dSalesDB -iLoopingCustomers.sql
start sqlcmd -S(local)\SQL2012Dev01 -dSalesDB -iLoopingCustomers.sql
start sqlcmd -S(local)\SQL2012Dev01 -dSalesDB -iLoopingCustomers.sql
start sqlcmd -S(local)\SQL2012Dev01 -dSalesDB -iLoopingCustomers.sql
start sqlcmd -S(local)\SQL2012Dev01 -dSalesDB -iLoopingCustomers.sql
start sqlcmd -S(local)\SQL2012Dev01 -dSalesDB -iLoopingCustomers.sql
start sqlcmd -S(local)\SQL2012Dev01 -dSalesDB -iLoopingCustomers.sql
start sqlcmd -S(local)\SQL2012Dev01 -dSalesDB -iLoopingCustomers.sql
start sqlcmd -S(local)\SQL2012Dev01 -dSalesDB -iLoopingCustomers.sql
start sqlcmd -S(local)\SQL2012Dev01 -dSalesDB -iLoopingCustomers.sql
start sqlcmd -S(local)\SQL2012Dev01 -dSalesDB -iLoopingCustomers.sql
