USE AdventureWorks2012;


WITH MY_CTE AS
(
	SELECT SH.SalesOrderID, SH.SubTotal,SH.Freight, CASE WHEN SH.SubTotal BETWEEN 1700 AND 1999 THEN 2000 - SH.SubTotal ELSE 0 END AS ORDERINCREASE, 
			CASE WHEN SH.SubTotal BETWEEN 1700 AND 1999 THEN 'ORDERINCREASE_LOWERFREIGHT' WHEN SH.SubTotal >=200 THEN 'NOORDERCHANGE_LOWERFREIGHT' ELSE 'NOCHANGE'  END AS SCENARIO,
			CASE WHEN SH.SubTotal >= 2000 THEN SH.Freight - 0.22 ELSE 0 END AS FREIGHTDECREASE, 
			SH.OrderDate
	FROM Sales.SalesOrderHeader AS SH
	INNER JOIN Person.Address AS PR ON SH.ShipToAddressID = PR.AddressID
	INNER JOIN Person.StateProvince AS SP ON SP.StateProvinceID = PR.StateProvinceID
	WHERE SP.Name = 'California' AND SH.OrderDate >= '20110701' AND SH.OrderDate < '20120701' 
),
MC AS
(
SELECT *, (ORDERINCREASE - FREIGHTDECREASE) AS NETGAIN
FROM MY_CTE 
)
SELECT SCENARIO, SUM(ORDERINCREASE), SUM(FREIGHTDECREASE), SUM(NETGAIN)
FROM MC
GROUP BY SCENARIO