SELECT  [session_id],
        [request_id],
        [scheduler_id],
        [dop],
        [request_time],
        [grant_time],
        [requested_memory_kb],
        [granted_memory_kb],
        [required_memory_kb],
        [used_memory_kb],
        [max_used_memory_kb],
        [query_cost],
        [timeout_sec],
        [resource_semaphore_id],
        [queue_id],
        [wait_order],
        [is_next_candidate],
        [wait_time_ms],
        [plan_handle],
        [sql_handle],
        [group_id],
        [pool_id],
        [is_small],
        [ideal_memory_kb]
FROM    sys.[dm_exec_query_memory_grants];
GO