SELECT  [id],
        [status],
        [path],
        [max_size],
        [stop_time],
        [max_files],
        [is_rowset],
        [is_rollover],
        [is_shutdown],
        [is_default],
        [buffer_count],
        [buffer_size],
        [file_position],
        [reader_spid],
        [start_time],
        [last_event_time],
        [event_count],
        [dropped_event_count]
FROM sys.[traces] AS t;