USE AdventureWorks2012;

SELECT PR.PersonType, SUM(CASE WHEN PEM.EmailAddress LIKE '%ADVENTURE-WORKS.COM%' THEN 1 ELSE 0 END) AS ADVDOM 
		,SUM(CASE WHEN PEM.EmailAddress LIKE '%ADVENTURE-WORKS.COM%' THEN 0 ELSE 1 END) AS NONADVDOM 
		,COUNT(*) AS TOTEA
FROM Person.Person AS PR
INNER JOIN Person.EmailAddress AS PEM ON PEM.BusinessEntityID = PR.BusinessEntityID
GROUP BY PR.PersonType
ORDER BY TOTEA DESC
