USE AdventureWorks2012;


SELECT DISTINCT YEAR(SO.OrderDate), MIN(SO.SubTotal) OVER (PARTITION BY YEAR(SO.OrderDate)), MAX(SO.SubTotal) OVER (PARTITION BY YEAR(SO.OrderDate)), 
	AVG(SO.SubTotal) OVER (PARTITION BY YEAR(SO.OrderDate)), PERCENTILE_DISC(0.5) WITHIN GROUP (ORDER BY SO.SubTotal) OVER (PARTITION BY YEAR(SO.OrderDate)) AS MEDIAN
FROM Sales.SalesOrderHeader AS SO
--GROUP BY YEAR(SO.OrderDate)