USE AdventureWorks2012;

;WITH CTE AS
(
SELECT YEAR(DATEADD(MONTH, 6, SO.OrderDate)) AS FISCALYR, ST.Name, SUM(SO.SubTotal) AS TOT
	, ROW_NUMBER() OVER(PARTITION BY YEAR(DATEADD(MONTH, 6, SO.OrderDate)) ORDER BY SUM(SO.SubTotal) DESC) AS RN
FROM Sales.SalesTerritory AS ST
INNER JOIN Sales.SalesOrderHeader AS SO ON SO.TerritoryID = ST.TerritoryID
WHERE OrderDate >= '20100701' AND OrderDate < '20120701'
GROUP BY YEAR(DATEADD(MONTH, 6, SO.OrderDate)), ST.Name
)
SELECT *
FROM CTE
WHERE RN<3