USE AdventureWorks2012;

--AGAIN, INSTEASD OF A SUBQUERY, IT WOULD HAVE BEEN BETTER TO USE A CASE STATEMENT AS BY USING SUB QUERY WE ARE QUERYING 
--THE TABLE REPEATEDLY AND THAT IS NOT EFFICIENT
--HAVE USED CASE BELOW FOR PART 2
SELECT COUNT(*)
	,100.0 * (SELECT COUNT(*) FROM HumanResources.Employee AS EM1 WHERE EM1.Gender = 'M' AND EM1.CurrentFlag = 1 ) /COUNT(*) 
	,100.0 * (SELECT COUNT(*) FROM HumanResources.Employee AS EM1 WHERE EM1.Gender = 'F' AND EM1.CurrentFlag = 1) / COUNT(*)
	,SUM(DATEDIFF(MONTH, EM.HireDate, SYSDATETIME())) / COUNT(*)
FROM HumanResources.Employee AS EM
--INNER JOIN HumanResources.EmployeePayHistory AS EP ON EP.BusinessEntityID = EM.BusinessEntityID
WHERE EM.CurrentFlag = 1


;WITH CTE AS
(
SELECT EM.Gender, EM.HireDate, EM.CurrentFlag, EM.LoginID, 
		NTILE(4) OVER(ORDER BY DATEDIFF(MONTH, EM.HireDate, SYSDATETIME())) AS TILE
FROM HumanResources.Employee AS EM
)
SELECT COUNT(*)
	,100.0 * SUM(CASE WHEN EM.Gender = 'M' THEN 1 ELSE 0 END ) /COUNT(*) 
	,100.0 * SUM(CASE WHEN EM.Gender = 'F' THEN 1 ELSE 0 END ) /COUNT(*) 
	,SUM(DATEDIFF(MONTH, EM.HireDate, SYSDATETIME())) / COUNT(*)
	,EM.TILE
FROM CTE AS EM
GROUP BY TILE

