USE AdventureWorks2012;

;WITH CTE AS
(SELECT SHR.SalesOrderID, SR.Name, CASE WHEN COUNT(SR.Name) OVER(PARTITION BY SHR.SalesOrderID) > 1 THEN 'CONTRIBUTING' ELSE 'EXCLUSIVE' END AS REASONINF
FROM Sales.SalesOrderHeaderSalesReason AS SHR
INNER JOIN Sales.SalesReason AS SR ON SR.SalesReasonID = SHR.SalesReasonID
)
SELECT CTE.Name, CTE.REASONINF, COUNT(CTE.SalesOrderID)
FROM CTE 
GROUP BY CTE.Name, CTE.REASONINF