USE AdventureWorks2012;

WITH CTE AS
(
SELECT 
	YEAR (DATEADD (MONTH, 6, OrderDate)) AS FISCALYEAR,	SH.OrderDate AS ORDERDATE, SH.SalesOrderNumber, SH.SubTotal
FROM Sales.SalesOrderHeader AS SH
WHERE SH.OrderDate >= '20100701' AND SH.OrderDate < '20120701'
)
,CTE2 AS
(
SELECT CTE.*,
	ROW_NUMBER() OVER(PARTITION BY FISCALYEAR ORDER BY ORDERDATE) AS RN
	,SUM(SubTotal) OVER(PARTITION BY FISCALYEAR ORDER BY ORDERDATE ROWS UNBOUNDED PRECEDING) AS RUNNINGTOTAL
FROM CTE
),
CTE3 AS
(
SELECT FISCALYEAR, MIN(RN) AS RN
FROM CTE2
WHERE RUNNINGTOTAL > 100000
GROUP BY FISCALYEAR
)
SELECT CTE2.*
FROM CTE2 INNER JOIN CTE3 ON CTE2.FISCALYEAR = CTE3.FISCALYEAR AND CTE2.RN = CTE3.RN
--ORDER BY RN
--OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY