USE AdventureWorks2012;


SELECT DISTINCT Size
FROM Production.Product
WHERE ISNUMERIC (Size) = 0 AND 
	Size IS NOT NULL

SELECT PR.SIZE, SUM(PI.Quantity) AS CUR, SUM(PI.Quantity) - 1000 AS ADDITIONAL
FROM Production.Product AS PR
INNER JOIN Production.ProductInventory AS PI ON PI.ProductID = PR.ProductID
WHERE PR.Size IN --WOULD BE MORE EFFICIENT TO USE USE WHERE CLAUSE ON OUTER QUERY THAN TO USE IN HERE
		(SELECT DISTINCT Size FROM Production.Product WHERE ISNUMERIC (Size) = 0 AND Size IS NOT NULL)
GROUP BY PR.Size

