USE AdventureWorks2012;

SELECT * 
FROM (SELECT TOP(5) SOH.SalesPersonID, SUM(SOH.SubTotal) AS REV, ROW_NUMBER() OVER(ORDER BY SUM(SOH.SubTotal) DESC) AS RNK
		FROM Sales.SalesOrderHeader AS SOH
		WHERE SOH.SalesPersonID IS NOT NULL AND SOH.OrderDate >= '20120101' AND SOH.OrderDate < '20130101'
		GROUP BY SOH.SalesPersonID
		ORDER BY REV DESC
) AS TOPSP

INNER JOIN (

SELECT * 
FROM (SELECT TOP(5) SOH.SalesPersonID, SUM(SOH.SubTotal) AS REV, ROW_NUMBER() OVER(ORDER BY SUM(SOH.SubTotal) ) AS RNK
		FROM Sales.SalesOrderHeader AS SOH
		WHERE SOH.SalesPersonID IS NOT NULL AND SOH.OrderDate >= '20120101' AND SOH.OrderDate < '20130101'
		GROUP BY SOH.SalesPersonID
		ORDER BY REV 
) AS BOTTOMSP) AS S ON S.RNK = TOPSP.RNK
